---

- hosts: all
  become: true
  pre_tasks:

   - name: install update (CentOS)
     tags: always
     dnf:
       update_only: yes
       update_cache: yes
     when: ansible_distribution == "CentOS"


   - name: install update (Ubuntu)
     tags: always
     apt:
       upgrade: dist
       update_cache: yes
     when: ansible_distribution == "Ubuntu"



- hosts: web_servers
  become: true
  tasks:


   - name: install apache2 and php for Ubuntu servers
     tags: always
     apt:
       name:
         - apache2
         - libapache2-mod-php
       state: latest
       update_cache: yes
     when: ansible_distribution == "Ubuntu"


   - name: install apache and php for CentOS servers
     tags: always
     dnf:
       name:
         - httpd
         - php
       state: latest
     when: ansible_distribution == "CentOS"


     name: copy default html file for site
     tags: apache,apache2,httpd
     copy:
       src: default_site html
       dest: /var/www/html/index.html
       owner: root
       group: root
       model: 0644


- hosts: db_servers
  become: true
  tasks:


   - name: install mariadb package (CentOS)
     tags: always
     dnf:
       name: mariadb
       state: latest
     when: ansible_distribution == "CentOS"


   - name: install mariadb package (Ubuntu)
     apt:
       name: mariadb-server
       state: latest
     when: ansible_distribution == "Ubuntu"


- hosts: samba package
  become: true
  tasks:

   - name: install samba package
     package:
       name: samba
       state: latest

