- name: add ssh key for gaya
  tags: always
  authorized_key:
    user: gaya
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICx5Z1x1QnJafVtQ+6PLnmPLWJuj0dPwsGbQKEIo+UZZ @ansible@"
- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
